export const adminData = {
    data: {
        id: '',
        firstname: '',
        lastname:'',
        mobile:'',
        emailid:'',
        username: '',
        password: '',
        dob:'',
        jobtitle:'',
        address:'',
        location:'',
        city:'',
        pincode:'',
        state:'',
        country:'',
        status: '',
        aadhar:'',
        pan:'',
        qualification:'',
        father_spouse:'',
        ref_1:'',
        ref_2:''

    },
    error: {
        id: '',
        firstname: '',
        lastname:'',
        mobile:'',
        emailid:'',
        username: '',
        password: '',
        dob:'',
        jobtitle:'',
        address:'',
        location:'',
        city:'',
        pincode:'',
        state:'',
        country:'',
        status: '',
        aadhar:'',
        pan:'',
        qualification:'',
        father_spouse:'',
        ref_1:'',
        ref_2:''
    },
    valid: {
        id: false,
        firstname: false,
        lastname: false,
        mobile: false,
        emailid: false,
        username: false,
        password: false,
        dob: false,
        jobtitle: false,
        address: false,
        location: false,
        city: false,
        pincode: false,
        state: false,
        country: false,
        status: false,
        aadhar: false,
        pan: false,
        qualification: false,
        father_spouse: false,
        ref_1: false,
        ref_2: false
    },
    label: {
        id: 'id',
        firstname: 'First Name',
        lastname:'Last Name',
        mobile:'Mobile Number',
        emailid:'Email Id',
        username: 'Username',
        password: 'Password',
        dob:'D.O.B',
        jobtitle:'Job Title',
        address:'Address',
        location:'Location',
        city:'City',
        pincode:'Pincode',
        state:'State',
        country:'Country',
        status: 'Status',
        aadhar:'Aadhar Number',
        pan:'Pancard',
        qualification:'Qualification',
        father_spouse:'Father/Spouse Mobile Number',
        ref_1:'Reference Number',
        ref_2:'Reference Number'
    },
    name: {
        id: 'id',
        firstname: 'firstname',
        lastname:'lastname',
        mobile:'mobile',
        emailid:'emailid',
        username: 'username',
        password: 'password',
        dob:'dob',
        jobtitle:'jobtitle',
        address:'address',
        location:'location',
        city:'city',
        pincode:'pincode',
        state:'state',
        country:'country',
        status: 'status',
        aadhar:'aadhar',
        pan:'pan',
        qualification:'qualification',
        father_spouse:'father_spouse',
        ref_1:'ref_1',
        ref_2:'ref_2'
    }
}

export const adminModel = [
    {
         'id': '1',
        'firstname': 'Sathish',
        'lastname':'S',
        'mobile':'8047859620',
        'emailid':'abc@ss.com',
        'username': 'sk',
        'password': 'password',
        'dob':'24/11/1997',
        'jobtitle':'admin',
        'address':'sssss',
        'location':'lsss',
        'city':'city',
        'pincode':'607801',
        'state':'GOA',
        'country':'INDIA',
        'status': 'status',
        'aadhar':'123456789321',
        'pan':'ABCD1234E',
        'qualification':'qualification',
        'father_spouse':'9876543210',
        'ref_1':'9876543210',
        'ref_2':'9876543210'
    },
    
];
