export const driverData = {
    data: {
        id: '',
        mobile: '',
        email: '',
        aadhar: '',
        name: '',
        father_name: '',
        dob: '',
        gender: '',
        marital_status: '',
        blood_group: '',
        qualification: '',
        experience: '',
        previous_work: '',
        c_address: '',
        c_city: '',
        c_pincode: '',
        c_state: '',
        c_country: '',
        p_address: '',
        p_city: '',
        p_pincode: '',
        p_state: '',
        p_country: '',
        languages: '',
        e_number: '',
        e_name: '',
        e_relation: '',
        status: '',
        l_no: '',
        l_expiry: '',
        l_type: '',
        l_badge: '',
        l_badge_expiry: '',
        l_state: '',
        deleted_at:''
    },
    error: {
        
        mobile: '',
        email: '',
        aadhar: '',
        name: '',
        father_name: '',
        dob: '',
        gender: '',
        marital_status: '',
        blood_group: '',
        qualification: '',
        experience: '',
        previous_work: '',
        c_address: '',
        c_city: '',
        c_pincode: '',
        c_state: '',
        c_country: '',
        p_address: '',
        p_city: '',
        p_pincode: '',
        p_state: '',
        p_country: '',
        languages: '',
        e_number: '',
        e_name: '',
        e_relation: '',
        l_no: '',
        l_expiry: '',
        l_type: '',
        l_badge: '',
        l_badge_expiry: '',
        l_state: '',
    },
    valid: {
        
        mobile: false,
        email: false,
        aadhar: false,
        name: false,
        father_name: false,
        dob: false,
        gender: false,
        marital_status: false,
        blood_group: false,
        qualification: false,
        experience: false,
        previous_work: false,
        c_address: false,
        c_city: false,
        c_pincode: false,
        c_state: false,
        c_country: false,
        p_address: false,
        p_city: false,
        p_pincode: false,
        p_state: false,
        p_country: false,
        languages: false,
        e_number: false,
        e_name: false,
        e_relation: false,
        l_no: false,
        l_expiry: false,
        l_type: false,
        l_badge: false,
        l_badge_expiry: false,
        l_state: false,
    },
    label: {
        
        mobile: 'Mobile',
        email: 'Email',
        aadhar: 'Aadhar',
        name: 'Name',
        father_name: 'Father Name',
        dob: 'D.O.B',
        gender: 'Gender',
        marital_status: 'Marital Status',
        blood_group: 'Blood Group',
        qualification: 'Qualification',
        experience: 'Experience',
        previous_work: 'Previous Work',
        c_address: 'Communication Address',
        c_city: 'City',
        c_pincode: 'Pincode',
        c_state: 'State',
        c_country: 'Country',
        p_address: 'Permanent Address',
        p_city: 'City',
        p_pincode: 'Pincode',
        p_state: 'State',
        p_country: 'Country',
        languages: 'Languages Known',
        e_number: 'Emergency Person Number',
        e_name: 'Emergency Person Name',
        e_relation: 'Emergency Person Relation',
        l_no: 'License Number',
        l_expiry: 'License Expiry Date',
        l_type: 'License Type',
        l_badge: 'License Badge Number',
        l_badge_expiry: 'License Bage Expiry',
        l_state: 'License Issued State',
    },
    name: {
        
        mobile: 'mobile',
        email: 'email',
        aadhar: 'aadhar',
        name: 'name',
        father_name: 'father_name',
        dob: 'dob',
        gender: 'gender',
        marital_status: 'marital_status',
        blood_group: 'blood_group',
        qualification: 'qualification',
        experience: 'experience',
        previous_work: 'previous_work',
        c_address: 'c_address',
        c_city: 'c_city',
        c_pincode: 'c_pincode',
        c_state: 'c_state',
        c_country: 'c_country',
        p_address: 'p_address',
        p_city: 'p_city',
        p_pincode: 'p_pincode',
        p_state: 'p_state',
        p_country: 'p_country',
        languages: 'languages',
        e_number: 'e_number',
        e_name: 'e_name',
        e_relation: 'e_relation',
        l_no: 'l_no',
        l_expiry: 'l_expiry',
        l_type: 'l_type',
        l_badge: 'l_badge',
        l_badge_expiry: 'l_badge_expiry',
        l_state: 'l_state',
        deleted_at: "deleted_at"
    }
}


export const driverModel = [
    {
        id: 1,
        mobile: 1234567890,
        email: "test@test.com",
        aadhar: 123412341234,
        name: "Sathish",
        father_name: "Bharathi",
        dob: "1993-08-06",
        gender: "Male",
        marital_status: "Married",
        blood_group: "A+",
        qualification: "10th",
        experience: "10years",
        previous_work: "Chennai",
        c_address: "XXX",
        c_city: "xxxx",
        c_pincode: 600001,
        c_state: "Tamil Nadu",
        c_country: "India",
        p_address: "YYY",
        p_city: "yyyy",
        p_pincode: 600001,
        p_state: "Tamil Nadu",
        p_country: "India",
        languages: "English, Tamil, Hindi",
        e_number: 9999999999,
        e_name: "Deiva",
        e_relation: "friend",
        l_no: "G1234567",
        l_expiry: "2023-08-06",
        l_type: "HMV",
        l_badge: "X124545455",
        l_badge_expiry: "2023-08-06",
        l_state: "Tamil Nadu",
        deleted_at: "2021-10-28T13:26:22.000Z"
    }
]

export const LicenseData = {
    data: {
        s_type: ''
        
    },
    error: {
        s_type: ''
      
    },
    valid: {
        s_type: false
        
    },
    label: {
        s_type: 'Service type',
    },
    name: {
        s_type: 's_type',
        
    }
}

export const LicenseModel = [
    {
        
        l_no: "G1234567",
        l_expiry: "2023-08-06",
        l_type: "HMV",
        l_badge: "X124545455",
        l_badge_expiry: "2023-08-06",
        l_state: "Tamil Nadu"
    }
]

export const VehicleData = {
    data: {
        id: '',
        v_type: '',
        v_reg_no: '',
        v_model: '',
        v_make: '',
        v_engine_no: '',
        v_chassis_no: '',
        v_manufacture: '',
        v_roadtax_expiry: '',
        v_insurance_expiry: '',
        v_permit_expiry: '',
        v_fc_expiry: '',
    },
    error: {
        id: '',
        v_type: '',
        v_reg_no: '',
        v_model: '',
        v_make: '',
        v_engine_no: '',
        v_chassis_no: '',
        v_manufacture: '',
        v_roadtax_expiry: '',
        v_insurance_expiry: '',
        v_permit_expiry: '',
        v_fc_expiry: '',
    },
    valid: {
        id: false,
        v_type: false,
        v_reg_no: false,
        v_model: false,
        v_make: false,
        v_engine_no: false,
        v_chassis_no: false,
        v_manufacture: false,
        v_roadtax_expiry: false,
        v_insurance_expiry: false,
        v_permit_expiry: false,
        v_fc_expiry: false,
    },
    label: {
         id: 'id',
        v_type: 'Vehicle Type',
        v_reg_no: 'Vehicle Registration No.',
        v_model: 'Vehicle Model',
        v_make: 'Vehicle Make',
        v_engine_no: 'Vehicle Engine No.',
        v_chassis_no: 'Vehicle Chassis No.',
        v_manufacture: 'Vehicle Manufacture',
        v_roadtax_expiry: 'Vehicle RoadTax Expiry',
        v_insurance_expiry: 'Vehicle Insurance Expiry',
        v_permit_expiry: 'Vehicle Permit Expiry',
        v_fc_expiry: 'Vehicle FC Expiry',
    },
    name: {
        id: 'id',
        v_type: 'v_type',
        v_reg_no: 'v_reg_no',
        v_model: 'v_model',
        v_make: 'v_make',
        v_engine_no: 'v_engine_no',
        v_chassis_no: 'v_chassis_no',
        v_manufacture: 'v_manufature',
        v_roadtax_expiry: 'v_roadtax_expiry',
        v_insurance_expiry: 'v_insurance_expiry',
        v_permit_expiry: 'v_permit_expiry',
        v_fc_expiry: 'v_fc_expiry',
    }
}


export const VehicleModel = [
    {
        id: "1",
        v_type: "Car",
        v_reg_no: "A165465",
        v_model: "CIVIC",
        v_make: "Honda",
        v_engine_no: "AB1234",
        v_chassis_no: "B4321",
        v_manufacture: "2010",
        v_roadtax_expiry: "2023-01-01",
        v_insurance_expiry: "2023-02-01",
        v_permit_expiry: "2023-03-01",
        v_fc_expiry: "2023-04-01",
    }
]

export const DownloadData = {
    data: {
        id:'',
        driver_id:'',
        profile_photo:'',
        aadhar_card:'',
        pan_card:'',
        license:'',
        road_tax:'',
        permit:'',
        fc_certificate:'',
        insurance:'',
        lease_copy:'',
        noc:'',
        rc_book:'',
        vehicle_photo:'',
        license_suspend:'',
        license_penalty:'',
        profile_photo_approved: '',
        aadhar_card_approved: '',
        pan_card_approved: '',
        license_approved: '',
        road_tax_approved: '',
        permit_approved: '',
        fc_certificate_approved: '',
        insurance_approved: '',
        lease_copy_approved: '',
        noc_approved: '',
        rc_book_approved: '',
        vehicle_photo_approved: '',
        license_suspend_approved: '',
        license_penalty_approved: ''
    },
    
}

export const DriverId = {
    data: {
    
        driver_id:''
        
    },
    
}


export const DownloadModel = [
    {
        id:1,
        driver_id:1,
        profile_photo:"profile_photo.jpg",
        aadhar_card:"aadhar_card.pdf",
        pan_card:"pan_card.jpg",
        license:"license.jpg",
        road_tax:"road_tax.jpg",
        permit:"permit.jpg",
        fc_certificate:"fc_certificate.jpg",
        insurance:"insurance.jpg",
        lease_copy:"lease_copy.jpg",
        noc:"noc_jpg",
        rc_book:"rc_book.jpg",
        vehicle_photo:"vehicle_photo.jpg"
    }
]