export const FranchiseData = {
    data: {
        name: '',
        username: '',
        password: '',
        email: '',
        mobile: '',
        address: '',
        pincode: '',
        state: '',
        country: '',
        pan_no: '',
        aadhar_no: '',
        bank_ac_no: '',
        bank_ac_type: '',
        bank_name: '',
        bank_branch: '',
        bank_ifsc: '',
        status: ''
    },
    error: {
        name: '',
        username: '',
        password: '',
        email: '',
        mobile: '',
        address: '',
        pincode: '',
        state: '',
        country: '',
        pan_no: '',
        aadhar_no: '',
        bank_ac_no: '',
        bank_ac_type: '',
        bank_name: '',
        bank_branch: '',
        bank_ifsc: '',
        status: ''
    },
    valid: {
        name: false,
        username: false,
        password: false,
        email: false,
        mobile: false,
        address: false,
        pincode: false,
        state: false,
        country: false,
        pan_no: false,
        aadhar_no: false,
        bank_ac_no: false,
        bank_ac_type: false,
        bank_name: false,
        bank_branch: false,
        bank_ifsc: false,
        status: false
    },
    label: {
        name: 'Name',
        username: 'Username',
        password: 'Password',
        email: 'Email',
        mobile: 'Mobile',
        address: 'Address',
        pincode: 'Pincode',
        state: 'State',
        country: 'Country',
        pan_no: 'Pan No',
        aadhar_no: 'Aadhar No.',
        bank_ac_no: 'Bank Account No.',
        bank_ac_type: 'Bank Account Type',
        bank_name: 'Bank Name',
        bank_branch: 'Bank Branch',
        bank_ifsc: 'Bank IFSC',
        status: 'Status'
    },
    name: {
        name: 'name',
        username: 'username',
        password: 'password',
        email: 'email',
        mobile: 'mobile',
        address: 'address',
        pincode: 'pincode',
        state: 'state',
        country: 'country',
        pan_no: 'pan_no',
        aadhar_no: 'aadhar_no',
        bank_ac_no: 'bank_ac_no',
        bank_ac_type: 'bank_ac_type',
        bank_name: 'bank_name',
        bank_branch: 'bank_branch',
        bank_ifsc: 'bank_ifsc',
        status: 'status'
    }
}


export const FranchiseModel = [
    {
        "id": 1,
        "name": "sathish",
        "username": "sathish",
        "password": "1234",
        "email": "007sathishkumar@gmail.com",
        "mobile": "9952176665",
        "address": 'XXXXXXX',
        "pincode": '606706',
        "state": 'Tamil Nadu',
        "country": 'India'
    },
];
